### PR TITLE
Feature/linuxfs

### PR DESCRIPTION
**Pull request by eitch**

### CODE REVIEW

**Comment by savageautomate** [comment]
FYI, fixed CI build errors

**Comment by eitch** [comment]
I have now managed to fix a few more issues. The code finally reads and writes from the I2C bus. I'll need to do some more testing, but others can now test it too.

**Comment by FDelporte** [comment]
Nice work! Looking forward to see example :-)

**Review by FDelporte — APPROVED** [review]
Full trust in the work of @eitch

**Pull request merged**
