### PR TITLE
[Project] Use slf4j-api 1.7.x

### PR DESCRIPTION
**Pull request by eitch**
Simple, change to 1.7.x version of slf4j, so we don't use snapshot version

### CODE REVIEW

**Comment by FDelporte** [comment]
Seems Travis build is still reporting an error: 
[ERROR] /home/travis/build/Pi4J/pi4j-v2/plugins/pi4j-plugin-pigpio/src/test/java/com/pi4j/plugin/pigpio/test/gpio/digital/TestDigitalInputUsingTestHarness.java:[63,44] package org.slf4j.simple does not exist

**Comment by eitch** [comment]
Hey Frank

That doesn't make sense, since the code is correct:

image

**Comment by FDelporte** [comment]
@eitch another reason to dump Travis? ;-)

**Review by FDelporte — APPROVED** [review]
Ok, will create new ticket to either remove commented lines, or reenable and use them instead of system.out

**Pull request merged**
