### PR TITLE
FIX: Issue #27; I2CRegister.write ignores length value

### PR DESCRIPTION
**Pull request by savageautomate**
applied changes per @hackerjimbo ref: https://github.com/Pi4J/pi4j-v2/issues/27#issuecomment-655337273 for Issue #27

### CODE REVIEW

**Comment by hackerjimbo** [comment]
This is embarrasing! My git-fu isn't up to grabbing this branch. I tried following the instructions to “bring in the changes and test” but got an error on the git checkout (fatal: 'origin/issue/#27' is not a commit and a branch 'issue/#27' cannot be created from it). Any ideas? Apart from that I _really_ ought to learn more git.

**Comment by savageautomate** [comment]
If you have made any modifications in your current branch, you will have to either revert them or `stash` them to get back to the unmodified `master` branch..  

```
git stash
```

Next do a git pull to pull in all the latest changes and new branches:
```
git pull
```
Next, to switch to the new branch, use the `checkout` command.
```
git checkout issue/#27
```

This will pull in the commits where I made the changes for the correct `length` check.  This however, will **not** pull the changes related to compiling for the ARMv6. 

Thanks, Robert

**Comment by hackerjimbo** [comment]
That last command, `git checkout issue/#27`, gave me the error `error: pathspec 'issue/#27' did not match any file(s) known to git`. That's what confused me when I tried it before.

**Comment by FDelporte** [comment]
@hackerjimbo one rule for git if all else fails... :-) 
delete your local copy completely and just check out again from 

`git clone https://github.com/Pi4J/pi4j-v2.git`

**Comment by hackerjimbo** [comment]
Well I've got some good news, and I've got some bad news.

I ran it on a machine _without_ the attached device (too see what would happen). The good news is that there is no longer an error being raised do to the length.

The bad news is that even though the I2C write failed, the return value from the write function returns the number of bytes I wanted to write rather than the number actually written (or an exception).

**Comment by hackerjimbo** [comment]
Oh, and some of the traces still refer to the size of the buffer and don't mention the offset and length. For example, `[main] TRACE com.pi4j.library.pigpio.impl.PiGpioNativeImpl - [I2C::WRITE] -> [0]; Register [64]; I2C Block [128 bytes]`.

**Comment by savageautomate** [comment]
> The bad news is that even though the I2C write failed, the return value from the write function returns the number of bytes I wanted to write rather than the number actually written (or an exception).

I was not able to track down in code where this could happen.  It might need to be traced out.  Try out the latest commits (in the JAR I forward to you) and lets see if the issues are resolved.     Thanks, Robert

**Pull request merged**
