### PR TITLE
fix unnecessary sting concatenation in logging statements; downgrade logging level to INFO in BAU places

### PR DESCRIPTION
**Pull request by ylexus**
#369

### CODE REVIEW

**Comment by FDelporte** [comment]
wow, thanks @ylexus, exactly the kind of review the logging needed! looks good af first sight, will dive in a bit deeper one of the next days

**Review by eitch — CHANGES_REQUESTED** [review]
Thanks for the cleanup, but you changes some of the loggers from warning to info. Please undo that.

**Comment by FDelporte** [comment]
> Thanks for the cleanup, but you changes some of the loggers from warning to info. Please undo that.

@eitch see ticket #369, some warnings at the start of the Pi4J context could, in my opinion, indeed be changed to info. Others we will need to review.

**Comment by ylexus** [comment]
Yes, those changes to INFO was the whole point of this, the rest is just a side effect (automatic refactoring). Apologies, I should have mentioned the original issue is in the PR title and not in the first comment.

**Comment by eitch** [comment]
You mixed two things in the same commit. Can you please change that, then i'll merge your request. Commits should clearly define what they change, which is not the case here

**Comment by ylexus** [comment]
@eitch done

**Review by eitch — APPROVED** [review]
looks good

**Comment by ylexus** [comment]
Thanks, how often do you do releases? Just to know when to expect this change to be released.

**Comment by eitch** [comment]
As often as needed. We just did a 2.6.1. We might do a 2.6.2 soon.

**Pull request merged**
