### PR TITLE
Add Checkstyle Plugin to Enforce Import Rules

### PR DESCRIPTION
**Pull request by dariuszzbyrad**
While analyzing the project, I found several unused and redundant import statements. To improve the code quality and ensure that best practices are followed going forward, I have added the Checkstyle plugin with rules to:

- Detect and remove unused imports.
- Prevent redundant imports (e.g., duplicate imports of the same class).
- Disallow illegal imports such as sun.* packages by default.

This configuration will help maintain clean and compliant code, and the build will fail if any violations are detected.

### CODE REVIEW

**Comment by FDelporte** [comment]
Thanks @dariuszzbyrad! I'm all in favor of cleaner code, so this looks great. Asking for second opinion to Tom and/or Eitch so we can merge this.

**Review by taartspi — APPROVED** [review]
Thanks, this is a good idea to help keep the code clean.    You created a new _config_ directory with the context _checkstyle_.   Do you see more config file types  are possible and these separate directories are needed ?           Tom

**Comment by dariuszzbyrad** [comment]
Yes, potentially at the config level, we could add tools like CodeNarc, PMD, SpotBugs, etc. Additionally, for Checkstyle specifically, we might include files like `suppressions.xml` and `suppressions-cpath.xml` to manage specific rule exceptions.

**Comment by taartspi** [comment]
Thanks for the response and the PR.  Tom

**Comment by eitch** [comment]
The issue looks fine, but we have to bear in mind, that our resources are limited. Adding new checks and then failing the build should not be a priority. I am always willing to look at PRs with new checks, where each new check is a new PR and the build doesn't fail with the new check.

If we can agree on this, then i find this a good change and am always for cleaner and better code.

**Review by eitch — APPROVED** [review]
This looks good

**Pull request merged**
